version: "3"

services:
  app-volumes:
    build: ./config/docker/image/app-volumes
    volumes: &appvolumes
      - .:/var/www/html:delegated
      - ~/.composer:/var/www/html/magento/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - ~/.ssh:/var/www/.ssh:delegated
      - ~/.ssh/config:/var/www/workaround
      - sockdata:/sock
      - app-vendor:/var/www/html/magento/vendor
      - app-generated:/var/www/html/magento/generated
      - app-var:/var/www/html/magento/var
      - pub-static:/var/www/html/magento/pub/static
      - pub-media:/var/www/html/magento/pub/media

  app:
    build: ./config/docker/image/nginx
    ports:
      - 80:8000
    links:
      - phpfpm
      - db
    volumes: *appvolumes
    depends_on:
      - app-volumes
      - phpfpm
      - db

  phpfpm:
    image: markoshust/magento-php:7.0-fpm-3
    links:
      - db
    volumes: *appvolumes
    depends_on:
      - db

  cron:
    image: markoshust/magento-php:7.0-fpm-3
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

  node:
      build: ./config/docker/image/nodejs-php
      links:
        - app
      volumes: *appvolumes
      environment:
        - NPM_CONFIG_PREFIX=/home/node/.npm-global # To avoid permission error on npm install. It tries to save it at /var/www (root is the owner)
      depends_on:
        - app

volumes:
  dbdata:
  sockdata:
  app-vendor:
  app-generated:
  app-var:
  pub-static:
  pub-media:

